# Import Packages

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import os

In [4]:
import tensorflow as tf

# Import Dataset

## Classic Method

In [26]:
from tensorflow.keras.preprocessing import image

In [27]:
import os

In [36]:
from tensorflow.keras.utils import img_to_array

In [37]:
training_data = []
for file_name in os.listdir(DATA_PATH) :
    path = os.path.join(DATA_PATH, file_name)
    img = image.load_img(path)
    img = img.resize([28, 28])
    training_data.append(img_to_array(img))

In [38]:
training_data = np.reshape(training_data,(-1,28,28,3))
training_data = training_data.astype(np.float32)
training_data = training_data / 127.5 - 1.

In [41]:
from tensorflow.data import Dataset

In [42]:
BUFFER_SIZE = 60000
BATCH_SIZE = 256

In [43]:
train_dataset = Dataset.from_tensor_slices(training_data).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

In [44]:
train_dataset

<BatchDataset element_spec=TensorSpec(shape=(None, 28, 28, 3), dtype=tf.float32, name=None)>

## Tensorflow like method

In [6]:
from tensorflow.keras.utils import image_dataset_from_directory

path = '/Users/theopinto--dalle/code/35m5loKiUe/LeWaGAN/LeWaGAN/raw_data/'

dataset_test = image_dataset_from_directory(path, image_size=(28,28), labels=None, batch_size=None)

dataset_test

Found 7009 files belonging to 1 classes.


<ShuffleDataset element_spec=TensorSpec(shape=(28, 28, 3), dtype=tf.float32, name=None)>

In [12]:
for i in dataset_test :
    print(i)
    break

2023-02-09 20:37:04.975677: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


tf.Tensor(
[[[  9.382651    0.6173482  13.785715 ]
  [  7.214283    8.857138   10.642853 ]
  [  4.         14.         13.       ]
  ...
  [ 21.657955   24.657955   29.657955 ]
  [ 11.790758   14.790758   19.790758 ]
  [ 20.474573   23.474573   28.474573 ]]

 [[  4.         14.         13.       ]
  [  0.          9.642853    8.642853 ]
  [  4.         14.         13.       ]
  ...
  [ 18.         21.         26.       ]
  [ 21.127573   24.127573   29.127573 ]
  [ 17.92865    20.92865    25.92865  ]]

 [[  4.913268   12.913268   14.913268 ]
  [  9.571426   17.571426   19.571426 ]
  [  2.0714264  12.071426   11.071426 ]
  ...
  [ 27.351967   30.351967   35.351967 ]
  [ 14.         17.         22.       ]
  [ 19.056116   22.056116   27.056116 ]]

 ...

 [[  2.         11.         10.       ]
  [  1.         10.          9.       ]
  [  2.         11.         10.       ]
  ...
  [105.209305   65.209305   63.20931  ]
  [ 70.311165   49.31117    48.31117  ]
  [ 73.71417    48.714172   51.71

### let's try to normalize the pictures

In [7]:
func = lambda x : x/255

In [8]:
n_dataset = dataset_test.map(map_func=func)

In [9]:
n_dataset

<MapDataset element_spec=TensorSpec(shape=(28, 28, 3), dtype=tf.float32, name=None)>

In [13]:
for i in n_dataset :
    print(i)
    break

tf.Tensor(
[[[0.07843138 0.18039216 0.16862746]
  [0.10588235 0.20392157 0.19215687]
  [0.07955181 0.17759103 0.16582632]
  ...
  [0.27030796 0.22324912 0.27030796]
  [0.12857142 0.18739495 0.19915967]
  [0.08085213 0.18281291 0.17889135]]

 [[0.14705886 0.24509807 0.23333336]
  [0.12016805 0.20644256 0.19859943]
  [0.1112045  0.20924371 0.19747901]
  ...
  [0.43091282 0.34855986 0.328952  ]
  [0.21518598 0.18313327 0.16190472]
  [0.2123051  0.2123051  0.20446195]]

 [[0.09887955 0.18515407 0.17731093]
  [0.08599441 0.18403362 0.17226891]
  [0.03165253 0.12969175 0.11792704]
  ...
  [0.5974793  0.52689105 0.44061655]
  [0.5443581  0.47769138 0.36788747]
  [0.316747   0.25792348 0.1677274 ]]

 ...

 [[0.4266707  0.48157266 0.37961185]
  [0.28235307 0.3529413  0.25882366]
  [0.20390119 0.27056786 0.23135218]
  ...
  [0.21344641 0.24089739 0.11958901]
  [0.0865548  0.22380969 0.19635871]
  [0.09041628 0.18845549 0.17669079]]

 [[0.40784314 0.48235294 0.3647059 ]
  [0.3866146  0.44543812 0

In [14]:
f_dataset = n_dataset.batch(batch_size=32, drop_remainder=False)
f_dataset

<BatchDataset element_spec=TensorSpec(shape=(None, 28, 28, 3), dtype=tf.float32, name=None)>